[build]
  command = "npm run build"
  publish = "dist"
[[redirect]]
  from = "/api/*"
  to = "https://test.matchlink.shop/:splat"
  status = 200
  force = true
[redirects.query]
  pathRewrite = "/api/"